### ISSUE TITLE
App crash. Server

### ISSUE THREAD

**Issue by userkilled** [hongui/FastAir#15]
FATAL EXCEPTION: DefaultDispatcher-worker-16
Process: com.mob.lee.fastair, PID: 13147
java.nio.channels.ClosedChannelException
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:235)
	at f2.a$d.x(Unknown Source:32)
	at u2.a.j(Unknown Source:11)
	at w5.v0.run(Unknown Source:88)
	at kotlinx.coroutines.internal.k.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.x(Unknown Source:0)
	at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14)
	at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
	Suppressed: w5.t0: [l2{Cancelling}@72b0a80, Dispatchers.IO]

------
I clicked by selecting all the files in one section, two files came out, clicked send and then went to the site of the running server and the application crashed.

The site of the server does not look at all.understand, to be honest...

Is it working at all?

**Comment by userkilled** [comment]
It was not possible to cause this crash again, most likely it is not permanent or the problem is deeper than the actions I described
